name: build and deploy jobs
on:
  workflow_call:
    inputs:
      build_source:
        description: source directory for build
        required: false 
        type: string
        default: ''
      build_destination:
        description: destination directory for build
        required: false 
        type: string
        default: _site
      sparse_checkout:
        description: action/checkout only selected directory
        required: false 
        type: string
        default: true 
      builder:
        description: type of builder
        required: false 
        type: string
        default: 'jekyll'
      deploy_to:
        description: site host type
        required: false 
        type: string
        default: gh-pages
jobs:
  build:
    # available images: https://github.com/actions/runner-images#available-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      - name: Setup Ruby 
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.5"
          bundler-cache: true
      - name: Setup Python 
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip" # caching pip dependencies
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: install and Build 
        env:
          JEKYLL_ENV: production
        # Outputs to the './_site' directory by default
        run: |
          pip3 install --upgrade nbconvert
          bundle exec jekyll build/
          --config _config.yml/
          --source ${{inputs.build_source}}/
          --destination ${{inputs.build_destination}}/
          --url ${{inputs.build_url}}/
          --baseurl ${{ steps.pages.outputs.base_path }}
      - name: Purge unused CSS 
        run: |
          npm install -g purgecss
          purgecss -c purgecss.config.js
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{inputs.build_destination}}
  deploy:
    if: inputs.deploy_to == 'gh-pages'
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
